---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: {{ .Values.global.image }}
    ports:
    - containerPort: 80
      protocol: TCP
---
