---
apiVersion: v1
kind: Namespace
metadata:
  name: xxx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: xxx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
---
